jobs:
  stale:
    permissions:
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v5
      with:
        days-before-close: -1
        days-before-issue-stale: -1
        days-before-pr-stale: 14
        debug-only: false
        exempt-draft-pr: true
        operations-per-run: 500
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: 'This PR has not had activity in the past 2 weeks, labeling
          it as stale. If the PR is waiting for review, notify the dev@lucene.apache.org
          list. Thank you for your contribution!

          '
name: Mark stale pull requests
on:
  repository_dispatch:
    types: trigger-ga___mark-stale-PRs.yml
