jobs:
  smokeTestRelease:
    env:
      LUCENE_RELEASE_DIR: /tmp/lucene-release-dir
      TMP_DIR: /tmp/lucene-tmp-dir
    if: (github.event_name == 'schedule' && github.repository == 'apache/lucene')
      || (github.event_name != 'schedule')
    name: Smoke test release on jdk ${{ matrix.java-version }}, ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        check-latest: true
        distribution: temurin
        java-package: jdk
        java-version: '${{ matrix.java-version }}

          21

          '
    - continue-on-error: true
      name: Echo diagnostic paths and locations
      run: 'echo "All installed JDKs:"

        set | grep "JAVA"


        echo "Gradle''s ''RUNTIME_JAVA_HOME'' JDK:"

        RUNTIME_JAVA_HOME_VAR=JAVA_HOME_`echo ${{ matrix.java-version }} | egrep --only
        "[0-9]+"`_X64

        echo ${RUNTIME_JAVA_HOME_VAR} points at ${!RUNTIME_JAVA_HOME_VAR}


        # This sets the environment variable and makes it available for subsequent
        job steps.

        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable

        echo "RUNTIME_JAVA_HOME=${!RUNTIME_JAVA_HOME_VAR}" >> "$GITHUB_ENV"

        '
    - continue-on-error: true
      name: Run buildAndPushRelease.py (--dev-mode)
      run: '# Assemble an unsigned release, in dev mode, publish locally.

        python3 ./dev-tools/scripts/buildAndPushRelease.py --dev-mode --push-local
        ${{ env.LUCENE_RELEASE_DIR }}

        '
    - continue-on-error: true
      name: 'Run smokeTestRelease.py (runtime java: ${{ matrix.java-version }})'
      run: "python3 -u dev-tools/scripts/smokeTestRelease.py \\\n  --not-signed \\\
        \n  --tmp-dir ${{ env.TMP_DIR }} \\\n  file://`realpath ${{ env.LUCENE_RELEASE_DIR\
        \ }}/lucene*` \\\n  -Ptests.filter=\"@skipall\"\n"
    - continue-on-error: true
      if: ${{ always() }}
      name: Store smoke tester logs
      uses: actions/upload-artifact@v4
      with:
        name: smoke-tester-logs-jdk-${{ matrix.java-version }}
        path: '${{ env.TMP_DIR }}/**/*.log

          '
    strategy:
      matrix:
        java-version:
        - '21'
        - 22-ea
        os:
        - ubuntu-latest
name: 'Run nightly: buildAndPushRelease and smokeTestRelease.py'
on:
  repository_dispatch:
    types: trigger-ga___run-nightly-smoketester.yml
