env:
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
jobs:
  checks:
    name: checks without tests (JDK ${{ matrix.java }} on ${{ matrix.os }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: ./.github/actions/prepare-for-build
    - continue-on-error: true
      name: Run gradle check (without tests)
      run: ./gradlew check -x test -Ptask.times=true --max-workers 2
    strategy:
      matrix:
        java:
        - '21'
        os:
        - ubuntu-latest
    timeout-minutes: 15
  tests:
    name: tests (JDK ${{ matrix.java }} on ${{ matrix.os }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: ./.github/actions/prepare-for-build
    - continue-on-error: true
      name: Run gradle tests
      run: ./gradlew test "-Ptask.times=true" --max-workers 2
    - continue-on-error: true
      name: List automatically-initialized gradle.properties
      run: cat gradle.properties
    strategy:
      matrix:
        java:
        - '21'
        os:
        - ubuntu-latest
    timeout-minutes: 30
name: 'Run checks: all modules'
on:
  repository_dispatch:
    types: trigger-ga___run-checks-all.yml
