env:
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
jobs:
  test:
    name: Extra regression tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: ./.github/actions/prepare-for-build
    - continue-on-error: true
      name: Run 'gradlew lucene/analysis/common check testRegressions'
      run: ./gradlew -p lucene/analysis/common check testRegressions
    timeout-minutes: 15
name: 'Run checks: module lucene/analysis/common'
on:
  repository_dispatch:
    types: trigger-ga___run-checks-mod-analysis-common.yml
