env:
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
jobs:
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: ./.github/actions/prepare-for-build
    - continue-on-error: true
      name: Run 'gradlew lucene/distribution.tests test' (on ${{ matrix.os }})
      run: ./gradlew -p lucene/distribution.tests test
    strategy:
      matrix:
        os:
        - macos-latest
    timeout-minutes: 15
name: 'Run checks: module lucene/distribution.tests'
on:
  repository_dispatch:
    types: trigger-ga___run-checks-mod-distribution.tests.yml
